[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_BASE_URL = "/"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# בנטליפיי זה לא נדרש עבור Next.js, ה-plugin יטפל בזה
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200 